[package]
name = "elements-miniscript"
version = "0.1.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>, Sanket Kanjalkar <sanket1729@gmail.com>"]
repository = "https://github.com/ElementsProject/elements-miniscript"
description = "Elements Miniscript: Miniscript, but for elements"
license = "CC0-1.0"
edition = "2018"

[features]
compiler = []
trace = []

unstable = []
serde = ["actual-serde", "bitcoin/serde"]
rand = ["bitcoin/rand"]

[dependencies]
bitcoin = "0.29.1"
elements = "0.21.0"
bitcoin-miniscript = {package = "miniscript", git = "https://github.com/rust-bitcoin/rust-miniscript", rev = "72dab64af741383d502cb2aad8c78d3a749e6d50"}

# Do NOT use this as a feature! Use the `serde` feature instead.
actual-serde = { package = "serde", version = "1.0", optional = true }

[dev-dependencies]
serde_json = "1.0"
elementsd = {version = "0.6.0", features=["0_21_0","bitcoind_22_0"]}
actual-rand = { package = "rand", version = "0.8.4"}
secp256k1 = {version = "0.24.0", features = ["rand-std"]}

[[example]]
name = "htlc"
required-features = ["compiler"]

[[example]]
name = "parse"

[[example]]
name = "sign_multisig"

[[example]]
name = "verify_tx"

[[example]]
name = "xpub_descriptors"

[[example]]
name = "taproot"
required-features = ["compiler"]
