[package]
name = "elements-miniscript"
version = "0.1.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>, Sanket Kanjalkar <sanket1729@gmail.com>"]
repository = "https://github.com/ElementsProject/elements-miniscript"
description = "Elements Miniscript: Miniscript, but for elements"
license = "CC0-1.0"

[features]
compiler = []
trace = []
unstable = []
default = []
use-serde = ["bitcoin/use-serde", "serde"]
rand = ["bitcoin/rand"]

[dependencies]
bitcoin = {git = "https://github.com/rust-bitcoin/rust-bitcoin", rev = "efa9555ebdc78130b01a8a5ecd554ab922708622"}
elements = {git = "https://github.com/sanket1729/rust-elements", rev = "1cd21cb93880211fd90958f380890a36213aaab1"}
miniscript = {git = "https://github.com/sanket1729/rust-miniscript", rev = "b47a89bc14ad5d17dcff9cee0828615b9daaec57"}

[dev-dependencies]
serde_json = "<=1.0.44"
ryu = "<1.0.5"

[dependencies.serde]
version = "1.0"
optional = true

[[example]]
name = "htlc"
required-features = ["compiler"]

[[example]]
name = "parse"

[[example]]
name = "sign_multisig"

# [[example]]
# name = "verify_tx"

[[example]]
name = "xpub_descriptors"
