[package]
name = "elements-miniscript"
version = "0.1.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>, Sanket Kanjalkar <sanket1729@gmail.com>"]
repository = "https://github.com/ElementsProject/elements-miniscript"
description = "Elements Miniscript: Miniscript, but for elements"
license = "CC0-1.0"

[features]
compiler = []
trace = []
unstable = []
default = []
use-serde = ["bitcoin/use-serde", "serde"]
rand = ["bitcoin/rand"]

[dependencies]
bitcoin = "0.28.1"
elements = {git = "https://github.com/sanket1729/rust-elements", rev = "35110f6b5371319100913e6a6abed15f4637fe13"}
miniscript = {git = "https://github.com/rust-bitcoin/rust-miniscript", rev = "104eb55f13ce39c4043f24637f83411529a460ea"}

[dev-dependencies]
serde_json = "<=1.0.44"
ryu = "<1.0.5"

[dependencies.serde]
version = "1.0"
optional = true

[[example]]
name = "htlc"
required-features = ["compiler"]

[[example]]
name = "parse"

[[example]]
name = "sign_multisig"

[[example]]
name = "verify_tx"

[[example]]
name = "xpub_descriptors"
